export default [
  '用nodejs做过哪些项目？说下使用的技术和难点',
  '知道node哪些框架？优缺点？觉得设计比好的部分？',
  'koa的中间件模型如何实现的？',
  'promise、co、generator、async/await的实现？',
  '服务器开发网站安全有哪些？',
  'node如何利用多核？',
  'node的事件机制',
  'Buffer的使用',
  '网络层、DNS、IP，一个用户请求的具体过程？',
  'NGINX的使用，正向代理、反向代理、负载均衡以及理解',
  '如何做压测？压测工具+top+qps',
  '如何做跨域？JSONP的实现原理？自己实现一个nodeJS跨域中间件',
  'token、session、cookie',
  '如何防止SQL注入',
  'redis的基本使用',
  '加密算法有哪些？',
  'git的理解， rebase merge区别',
  '理解并设计rest/restful风格接口',
]
